[package]
name = "roughenough"
version = "0.1.1"
repository = "https://github.com/int08h/roughenough"
authors = ["Stuart Stock <stuart@int08h.com>"]
license = "Apache-2.0"
description = "A Roughtime secure time sync server written in Rust"
readme = "README.md"
keywords = ["roughtime", "cryptography", "crypto"]

[badges]
travis-ci = { repository = "int08h/roughenough", branch = "master" }

[dependencies]
byteorder = "1"
ring = "0.12"
untrusted = "0.5.1"
time = "0.1"
log = "0.3"
fern = "0.4"
yaml-rust = "0.3.5"
ctrlc = { version = "3.0", features = ["termination"] }

