[package]
name = "roughenough"
version = "0.1.0"
repository = "https://github.com/int08h/roughenough"
authors = ["Stuart Stock <stuart@int08h.com>"]
license = "Apache-2.0"

[dependencies]
byteorder = "1"
