[package]
name = "roughenough"
version = "0.1.0"
repository = "https://github.com/int08h/roughenough"
authors = ["Stuart Stock <stuart@int08h.com>"]
license = "Apache-2.0"
description = "A Roughtime secure time sync server written in Rust"

[dependencies]
byteorder = "1"
ring = "0.11.0"
untrusted = "0.5.0"
time = "0.1"
log = "0.3"
fern = "0.4"
yaml-rust = "0.3.5"
ctrlc = { version = "3.0", features = ["termination"] }

